In [1]:
import requests
from bs4 import BeautifulSoup
import time
from urllib import urlencode
import selenium.webdriver
import random
from pymongo import MongoClient
import json
import boto3
import pandas as pd
from parse_clean_store import (parse_route_page, parse_user)
from bs4 import BeautifulSoup
from matrix_recommender_prep import (clean_ratings, cold_start)
%load_ext autoreload
%autoreload 2

ImportError: No module named matrix_recommender_prep

In [2]:
client = MongoClient('mongodb://localhost:27017/')
db = client.route_html_collection
route_html_collection = db.route_html_collection
raw_data = route_html_collection.find()
df_route_html = pd.DataFrame(list(raw_data))
df_route_html.head()

,_id,html,route
0,58c87f8840b44102a84aedf9,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",30(1) Feet of Pleasure
1,58c87f9740b44102a84aedff,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",41 Feet of Pain
2,58c87fa640b44102a84aee05,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",5.5 Crack
3,58c87fb140b44102a84aee0b,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",5.6 crack
4,58c87fbc40b44102a84aee11,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",5.6 Dihedral

In [3]:
df_route_html.shape

(3626, 3)

In [4]:
client = MongoClient('mongodb://localhost:27017/')
db = client.user_html_collection
user_html_collection = db.user_html_collection
raw_data = user_html_collection.find()
df_user_html = pd.DataFrame(list(raw_data))
df_user_html.head()

,_id,html,username
0,58c87f9340b44102a84aedfd,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",adam winslow
1,58c87fa440b44102a84aee03,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",adam winslow
2,58c87fae40b44102a84aee09,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",Oscar Edge
3,58c87fb640b44102a84aee0f,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",Nick Drake
4,58c87fc340b44102a84aee15,"<!DOCTYPE html><html xmlns=""http://www.w3.org/...",Chris Culver

In [2]:
client = MongoClient('mongodb://localhost:27017/')
db = client.ratings_collection
ratings_collection = db.ratings_collection
raw_data = ratings_collection.find()
df_ratings = pd.DataFrame(list(raw_data))
df_ratings.head()

,_id,rating,route,username
0,58c87f8c40b44102a84aedfb,[1],30(1) Feet of Pleasure,[adam winslow ]
1,58c87f9d40b44102a84aee01,[1],41 Feet of Pain,[adam winslow ]
2,58c87fac40b44102a84aee07,"[1, 1, 1, 1]",5.5 Crack,"[CHopwood , Trevor. , Rickedge , Oscar Edge ]"
3,58c87fb440b44102a84aee0d,"[3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...",5.6 crack,"[Bianca P , Sandeep Kumar , Mike Brady , Tom B..."
4,58c87fbf40b44102a84aee13,"[2, 2, 2, 2, 1, 1, 1, 1, 1]",5.6 Dihedral,"[Jason Killgore , sqwirll , Dave Leydet , fort..."

In [4]:
df_ratings.shape

(3726, 4)

In [13]:
ratings_df = clean_ratings(df_ratings)
ratings_df.head()

,adam winslow,CHopwood,Trevor.,Rickedge,Oscar Edge,Bianca P,Sandeep Kumar,Mike Brady,Tom Bath,Clay Studer,...,Andrew Perkins,Mike dandy Patz,Travis England,Neilsonb,Ben Broche,Dustin Stephens,Curt Shannon,Cedar Wright,Detchy,Colin Moorhead
30(1) Feet of Pleasure,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41 Feet of Pain,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.5 Crack,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.6 crack,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.6 Dihedral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
ratings_df = ratings_df.T
ratings_df.head()

,30(1) Feet of Pleasure,41 Feet of Pain,5.5 Crack,5.6 crack,5.6 Dihedral,5.7,5.7 Face,A,A Crack,A MIGHTY WIND,...,TPMV (10% Meteorological Vinculation),Tradical,Tree Hugger,Trigger Finger,Trobability Pest,Twelve Gauge IQ,Under Arrest,Under the Influence,Unicorn Blues,Unknown
adam winslow,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHopwood,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Trevor.,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rickedge,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Oscar Edge,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
cold_start(ratings_df).head()

,30(1) Feet of Pleasure,41 Feet of Pain,5.5 Crack,5.6 crack,5.6 Dihedral,5.7,5.7 Face,A,A Crack,A MIGHTY WIND,...,Town Crier,TPMV (10% Meteorological Vinculation),Tradical,Tree Hugger,Trigger Finger,Trobability Pest,Twelve Gauge IQ,Under Arrest,Under the Influence,Unicorn Blues
adam winslow,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
CHopwood,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
Trevor.,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
Rickedge,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
Oscar Edge,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0

In [94]:
df = cold_start(df_ratings)
df.head()

,30(1) Feet of Pleasure,41 Feet of Pain,5.5 Crack,5.6 crack,5.6 Dihedral,5.7,5.7 Face,A,A Crack,A MIGHTY WIND,...,Town Crier,TPMV (10% Meteorological Vinculation),Tradical,Tree Hugger,Trigger Finger,Trobability Pest,Twelve Gauge IQ,Under Arrest,Under the Influence,Unicorn Blues
adam winslow,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
CHopwood,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
Trevor.,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
Rickedge,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0
Oscar Edge,1.0,1.0,1.0,2.029412,1.444444,2.0,1.692308,NaN,1.0,3.0,...,3.545455,3.928571,4.0,3.0,4.0,3.0,4.0,2.615385,2.0,4.0

In [95]:
from sklearn.decomposition import NMF

In [96]:
df_user_html.shape

NameError: name 'df_user_html' is not defined

In [97]:
soup = BeautifulSoup(html, 'html.parser')
page_tag = soup.find('div', {'id':'rspCol800'})
# make route dict
route_dict = {}
route_dict['name'] = page_tag.find('span', {'itemprop':'itemreviewed'}).text.encode('utf-8')
route_dict['grade'] = page_tag.find('span', {'class':'rateYDS'}).text
route_stars_text = soup.find('span', {'id':'starSummaryText'}).text.split('Average: ')
route_dict['average_rating'] = route_stars_text[1][:3]

NameError: name 'html' is not defined

In [98]:
def parse_route_page(html):
    '''
    takes a soup to parse
    returns dict of route info
    '''
    soup = BeautifulSoup(html, 'html.parser')
    page_tag = soup.find('div', {'id':'rspCol800'})
    # make route dict
    route_dict = {}
    route_dict['name'] = page_tag.find('span', {'itemprop':'itemreviewed'}).text
    route_dict['grade'] = clean_grade(page_tag)
    route_dict['average_rating'] = clean_average_rating(soup)
    
    for i, td in enumerate(page_tag.find('table').findAll('td')): 
        if td.text.split(':')[0] == 'Type':
            route_type = clean_route_type(page_tag.find('table').findAll('td')[i+1])
            route_dict['route_type_list'] = route_type[0]
            route_dict['pitches'] = route_type[1]
            route_dict['height'] = route_type[2]
            route_dict['uiaa'] = route_type[3]
            route_dict['misc'] = route_type[4]
        elif td.text.split(':')[0] == 'Original':
            route_dict['original_grade'] = clean_original_grade(page_tag.find('table').findAll('td')[i+1])
        elif td.text.split(':')[0] == 'FA':
            fa = page_tag.find('table').findAll('td')[i+1].text
            route_dict['FA'] = fa
        elif td.text.split(':')[0] == 'Season':
            season = page_tag.find('table').findAll('td')[i+1].text
            route_dict['season'] = season.encode('utf-8')
        elif td.text.split(':')[0] == 'Page Views':
            page_view = page_tag.find('table').findAll('td')[i+1].text
            route_dict['page_views'] = int(page_view.encode('utf-8').replace(',',''))
        elif td.text.split(':')[0] == 'Submitted By':
            sb1, sb2 = clean_submitted_by(page_tag.find('table').findAll('td')[i+1])
            route_dict['submitted_by'] = sb1
            route_dict['submitted_on'] = sb2
            
    return route_dict


def clean_route_type(tag):
    route_type = tag.text
    route_type = route_type.encode('utf-8').split(', ')
    list_of_types = ['Trad', 'Sport', 'TR', 'Alpine', 
                    'Ice', 'Boulder', 'Aid', 'Mixed']
    # initialize variables
    route_type_list = []
    pitches = float('nan')
    height = float('nan')
    uiaa = float('nan')
    misc = float('nan')
    for item in route_type:
        if item in list_of_types:
            route_type_list.append(item)
        elif 'pitches' in item:
            pitches = item.replace(' pitches', '')
        elif 'pitch' in item:
            pitches = item.replace(' pitch','')
        elif "'" in item:
            height = float(item.replace("'",''))
        elif 'Grade' in item:
            uiaa = item
        else:
            misc = item

    return route_type_list, pitches, height, uiaa, misc


def clean_submitted_by(page_tag):
    sb = page_tag.text
    sb = sb.encode('utf-8').split(' on ')
    return sb[0], sb[1]

def clean_original_grade(page_tag):
    grade = page_tag.text
    grade = grade.encode('utf-8').split('\xa0')[1]
    grade = grade.split('French')[0]
    return grade

def clean_grade(page_tag):
    grade = page_tag.find('span', {'class':'rateYDS'}).text
    grade = grade.encode('utf-8').split('\xa0')[1]
    return grade

def clean_average_rating(soup):
    route_stars_text = soup.find('span', {'id':'starSummaryText'}).text.split('Average: ')
    average_rating = route_stars_text[1][:3]
    if 'OK' in average_rating:
        average_rating = 1.0
    elif 's' in average_rating:
        average_rating = float(average_rating[0])
    else:
        average_rating = float(average_rating)
    return average_rating

In [21]:
df_route_html['_id'].shape == df_route_html['_id'].unique().shape

True

In [3]:
dict_list = []
for _id, html in enumerate(df_route_html['html']):
    dict_list.append(parse_route_page(_id, html))

In [23]:
df_routes = pd.DataFrame(dict_list)
df_routes.head(50)

,Aid,Alpine,Boulder,FA,Ice,Mixed,Sport,TR,Trad,average_rating,...,height,id,name,original_grade,page_views,pitches,season,submitted_by,submitted_on,uiaa
0,0,0,0,"Adam Winslow, Bill Coe, Kyle Silverman 3/20/09",0,0,0,0,1,1.0,...,41.0,0,30(1) Feet of Pleasure,5.6,588,1.0,NaN,adam winslow,"Aug 18, 2010",NaN
1,0,0,0,"Adam Winslow, Ujahn Davisson, Bill Coe, Jim Op...",0,0,0,0,1,1.0,...,41.0,1,41 Feet of Pain,5.5,642,1.0,NaN,adam winslow,"Aug 18, 2010",NaN
2,0,0,0,?,0,0,0,1,1,1.0,...,35.0,2,5.5 Crack,5.5,176,NaN,Afternoon shade,CHopwood,"Sep 2, 2013",NaN
3,0,0,0,,0,0,0,1,1,2.0,...,85.0,3,5.6 crack,5.6,1263,1.0,NaN,Tom Bath,"Dec 16, 2009",NaN
4,0,0,0,Unknown,0,0,0,1,1,1.4,...,30.0,4,5.6 Dihedral,5.6,678,1.0,NaN,chrishar Hargarten,"May 19, 2008",NaN
5,0,0,0,,0,0,1,0,0,2.0,...,40.0,5,5.7,5.7,326,NaN,NaN,Keenan Waeschle,"Mar 31, 2010",NaN
6,0,0,0,,0,0,0,1,1,1.7,...,95.0,6,5.7 Face,5.7,454,1.0,NaN,Mark Goodro,"Jun 18, 2013",NaN
7,0,0,0,,0,0,1,0,0,2.0,...,95.0,7,A,5.5,18,NaN,NaN,applewood,"May 28, 2013",NaN
8,0,0,0,,0,0,0,0,1,1.0,...,NaN,8,A Crack,5.7,51,NaN,NaN,Blitzo,"Oct 18, 2006",NaN
9,0,0,0,10/13,0,0,1,0,0,3.0,...,75.0,9,A MIGHTY WIND,5.3,39,NaN,NaN,applewood,"Oct 27, 2013",NaN
10,0,0,0,,0,0,0,0,1,1.8,...,250.0,10,A Slice of Ice,5.7,745,3.0,NaN,jdberndt,"Oct 12, 2011",NaN
11,0,0,0,Page Views:,0,0,1,0,0,2.0,...,40.0,11,A Walk in the Park,5.7,299,1.0,NaN,Colin Parker,"Apr 9, 2012",NaN
12,0,0,0,"George Zack, Danny Zack",0,0,0,0,1,2.0,...,320.0,12,Ablation Zone,5.7,367,3.0,NaN,George Zack,"Jun 25, 2014",Grade II
13,0,0,0,1/13/14,0,0,1,0,0,2.0,...,65.0,13,Abracadabra,5.5,15,NaN,NaN,applewood,"Dec 16, 2013",NaN
14,0,0,0,"5-2007 Bill Coe, Jim Opdycke",0,0,0,0,1,1.4,...,100.0,14,Afternoon Delight,5.7,87,1.0,NaN,Topher Dabrowski,"Apr 21, 2015",NaN
15,0,0,0,,0,0,1,0,0,2.0,...,80.0,15,Ah-Baloney,5.6,86,NaN,NaN,applewood,"May 27, 2013",NaN
16,0,0,0,"Gordon Briody, Viktor Kramar, 2000",0,0,0,0,1,1.6,...,100.0,16,Ain't Misbehavin',5.7,362,1.0,NaN,Matt. B.,"May 17, 2015",NaN
17,0,0,0,"Gordan Briody, Viktor Kramar 2003",0,0,1,0,0,1.6,...,100.0,17,Aisle of Sky,5.6,749,1.0,NaN,laurichj,"Sep 27, 2010",NaN
18,0,0,0,T. Nelson (1995),0,0,0,0,1,3.0,...,50.0,18,Alan Henshaw pre-memorial route,5.7,59,1.0,year round,Kyle Elliott,"Jan 17, 2017",NaN
19,0,0,0,,0,0,1,0,0,2.0,...,55.0,19,Alkahest,5.7,19,NaN,NaN,applewood,"Aug 26, 2014",NaN
20,0,0,0,"Leland Windham, Kurt Greenbaum",0,0,1,0,0,2.2,...,40.0,20,Altar of Sacrifice,5.7,1120,NaN,NaN,Ian Dickson,"Oct 26, 2009",NaN
21,0,0,0,,0,0,0,0,1,1.7,...,90.0,21,Another Notch in My Lipstick Case,5.7+,163,NaN,NaN,Morrismc,"Feb 6, 2011",NaN
22,0,0,0,,0,0,0,0,1,1.0,...,70.0,22,Apes in Capes,5.4,7,NaN,NaN,applewood,"Feb 16, 2015",NaN
23,0,0,0,"Windham, Kern, Massey, Ellis - 1999",0,0,1,0,0,1.0,...,45.0,23,Appraisal of My Cumbersome Carcass,5.7,130,NaN,NaN,Jeff Hebert,"Mar 17, 2014",NaN
24,0,0,0,,0,0,0,0,1,1.5,...,NaN,24,Apprentice Route,5.6,516,NaN,NaN,Scott Coldiron,"Jul 16, 2009",NaN
25,0,0,0,,0,0,1,0,0,2.0,...,95.0,25,Aqua Vitae,5.4,18,NaN,NaN,applewood,"May 27, 2013",NaN
26,0,0,0,,0,0,0,0,1,1.5,...,NaN,26,Aquarius,5.7,619,3.0,NaN,Eric Fjellanger,"Jul 16, 2012",NaN
27,0,0,0,,0,0,1,0,1,1.0,...,100.0,27,Armageddon,5.5,373,NaN,NaN,michael faith,"May 11, 2012",NaN
28,0,0,0,,0,0,1,0,0,1.0,...,100.0,28,Arrested Development,5.4,9,NaN,NaN,applewood,"May 27, 2013",NaN
29,0,0,0,,0,0,1,0,0,1.0,...,20.0,29,As You Wish,5.6,60,1.0,NaN,Dan Sulpizi,"Aug 16, 2016",Grade V
30,0,0,0,Kevin Pogue,0,0,1,0,0,2.3,...,NaN,30,Astroknot,5.7,66,NaN,NaN,Kemper Brightman,"Jun 1, 2014",NaN
31,0,0,0,,0,0,1,0,0,1.0,...,95.0,31,B,5.5,16,NaN,NaN,applewood,"May 28, 2013",NaN
32,0,0,0,"Linda Stretz, Julie Smith 90",0,0,0,0,1,1.5,...,80.0,32,B.S.,5.6,86,1.0,NaN,Nick Drake,"Jul 11, 2016",NaN
33,0,0,0,5/14,0,0,0,0,1,1.0,...,75.0,33,Baby Anarchist,5.3,13,NaN,NaN,applewood,"Feb 21, 2014",NaN
34,0,0,0,,0,0,1,0,0,1.0,...,90.0,34,Baby Rattler,5.7,8,NaN,NaN,applewood,"Mar 17, 2014",NaN
35,0,0,0,,0,0,1,0,0,1.6,...,70.0,35,Baby Steps,5.4,872,1.0,NaN,Tom Bath,"Oct 26, 2009",NaN
36,0,0,0,,0,0,0,0,1,1.5,...,70.0,36,Baby's Bottom,5.3,319,1.0,NaN,RCamper Camp,"Jul 13, 2014",NaN
37,0,0,0,Willl Parks '72,0,0,0,0,1,1.8,...,35.0,37,Back Tree Crack,5.7,469,NaN,NaN,Scott Coldiron,"Jun 8, 2009",NaN
38,0,0,0,?,0,0,0,0,1,1.6,...,30.0,38,Bag Ends,5.7,728,1.0,NaN,Peter Rakowitz,"May 6, 2012",NaN
39,0,0,0,,0,0,0,1,1,2.0,...,45.0,39,Ballscratcher,5.7,32,1.0,NaN,Pete Wojcik,"Jun 27, 2016",NaN
40,0,0,0,,0,0,0,0,1,2.0,...,95.0,40,BALSAM ROUTE,5.7,8,NaN,NaN,applewood,"Oct 30, 2013",NaN
41,0,0,0,Bryan Burdo,0,0,1,1,0,2.0,...,40.0,41,Bambino Buttress,5.6,151,NaN,NaN,Andrew Davidson,"Dec 10, 2014",NaN
42,0,0,0,,0,0,1,0,0,2.0,...,NaN,42,Bear in a Man Suit,5.5,40,NaN,NaN,Nick Sweeney,"Apr 18, 2016",NaN
43,0,0,0,"Kevin Pogue, Elisa Weinman",0,0,1,0,0,2.1,...,50.0,43,Beckey Route,5.7,1259,1.0,NaN,Eliza Penick,"Apr 12, 2009",NaN
44,0,1,0,"Fred Beckey, Jerry O'Neil, Charles Welsh 1946",0,0,0,0,1,3.1,...,NaN,44,Beckey Route (SW Face),5.6,30424,3.0,NaN,ScottH,"Feb 17, 2006 with updates\n from Marc Sarr...",Grade II
45,0,1,0,1946,1,0,0,0,1,4.0,...,1000.0,45,Beckey-Schmidtke,5.4,635,10.0,Summer,Abandoned User,"Aug 16, 2014",Grade IV
46,0,0,0,,0,0,1,0,0,2.0,...,70.0,46,Before and After Science,5.5,15,NaN,NaN,applewood,"Jun 7, 2013",NaN
47,0,0,0,7/9/10,0,0,1,0,0,3.0,...,100.0,47,Beginner's Mind,5.4,338,1.0,NaN,applewood,"May 26, 2013",NaN
48,0,0,0,,0,0,1,0,0,2.0,...,NaN,48,"Ben There, Done That",5.6,58,NaN,NaN,Nick Sweeney,"Apr 18, 2016",NaN
49,0,0,0,,0,0,0,0,1,2.0,...,30.0,49,Big Black Hen,5.5,49,1.0,NaN,BenR,"Jul 10, 2016",NaN

In [4]:
client = MongoClient('mongodb://localhost:27017/')
db = client.routes
routes = db.routes
routes.insert_many(dict_list)

In [12]:
raw = routes.find()
pd.DataFrame(list(raw)).head()

,Aid,Alpine,Boulder,FA,Ice,Mixed,Sport,TR,Trad,_id,...,grade,height,name,original_grade,page_views,pitches,season,submitted_by,submitted_on,uiaa
0,0,0,0,"Adam Winslow, Bill Coe, Kyle Silverman 3/20/09",0,0,0,0,1,58cc183e40b441224553a5f2,...,5.6,41.0,30(1) Feet of Pleasure,5.6,588,1.0,NaN,adam winslow,"Aug 18, 2010",NaN
1,0,0,0,"Adam Winslow, Ujahn Davisson, Bill Coe, Jim Op...",0,0,0,0,1,58cc183e40b441224553a5f3,...,5.5,41.0,41 Feet of Pain,5.5,642,1.0,NaN,adam winslow,"Aug 18, 2010",NaN
2,0,0,0,?,0,0,0,1,1,58cc183e40b441224553a5f4,...,5.5,35.0,5.5 Crack,5.5,176,NaN,Afternoon shade,CHopwood,"Sep 2, 2013",NaN
3,0,0,0,,0,0,0,1,1,58cc183e40b441224553a5f5,...,5.6,85.0,5.6 crack,5.6,1263,1.0,NaN,Tom Bath,"Dec 16, 2009",NaN
4,0,0,0,Unknown,0,0,0,1,1,58cc183e40b441224553a5f6,...,5.6,30.0,5.6 Dihedral,5.6,678,1.0,NaN,chrishar Hargarten,"May 19, 2008",NaN

In [56]:
df_routes.shape[0]

3626

In [57]:
df_routes['name'].unique().shape[0]

3463

In [85]:
unique_names = df_user_html['username'].unique().tolist()

In [86]:
type(unique_names)

list

In [88]:
dict_list = []
for html, name in zip(df_user_html['html'], df_user_html['username']):
    if name in unique_names:
        dict_list.append(parse_user(html))
        unique_names.remove(name)
df_users = pd.DataFrame(dict_list)
df_users.head(50)

,Aid:,Favorite Climbs:,Ice:,Likes to climb:,Other Interests:,Personal:,Sport:,Trad:,compliments,last_vist,member_since,name,point_rank,total_points
0,NaN,none specified,NaN,"Trad, Sport, TR climbs",none specified,"Lives in Pullman WA, 14 years old, Male",Leads 5.11a 6c 22 VII+ 22 E3 5c Follows 5...,Leads 5.8 5b 16 VI- 15 HVS 4c Follows 5.1...,,"Jan 30, 2017","Jun 21, 2016",Oscar Edge,"7,891",31
1,NaN,"NR Stuart, Rattletail, Outer Space, anything ...",Leads WI2 Follows WI5,"Trad, Sport, Gym climbs",Splitboarding,"Lives in Newcastle, WA, 36 years old, Male",Leads 5.11a 6c 22 VII+ 22 E3 5c Follows 5...,Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,,3 hours ago,"Jan 20, 2015",Nick Drake,"1,812",353
2,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,1 day ago,"Jul 7, 2014",Chris Culver,-none-,0
3,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs",none specified,"Lives in Silverdale, WA, Male",NaN,Leads 5.11b 6c 23 VIII- 23 E3 5c Follows ...,2,"Jun 4, 2015","Oct 11, 2010",Ethan Henderson,"1,084",630
4,NaN,none specified,Leads WI4 Follows WI5,"Trad, Sport climbs",none specified,"Lives in Soldotna, Alaska, 44 years old, Male",Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,,3 days ago,"Aug 21, 2014",Chris Walden,"1,764",367
5,NaN,none specified,NaN,none specified,none specified,"Lives in Tonasket, WA",NaN,NaN,,6 hours ago,"Aug 30, 2012",applewood,20,"11,385"
6,NaN,none specified,NaN,"Trad, Sport climbs","Martial arts, Herpetology, cooking","Lives in Everett, WA, 31 years old, Male",Leads 5.12a 7a+ 25 VIII+ 25 E5 6a Follows ...,Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,,9 hours ago,"Jul 14, 2015",Kyle Elliott,"2,066",295
7,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs",none specified,"Lives in North Bend, WA, 29 years old, Male",Leads 3rd 1- 1 I 1 M 1a Follows 4th 1 2 I...,Leads 3rd 1- 1 I 1 M 1a Follows 3rd 1- 1 ...,,7 hours ago,"Aug 4, 2013",Ryan Canfield,"2,535",225
8,NaN,Any alpine rock,NaN,"Trad, Sport, TR, Gym climbs","Mountaineering, skiing (alpine, tele, BC, XC,...",NaN,Leads 5.10c 6b 20 VII 20 E2 5b Follows 5....,Leads 5.8 5b 16 VI- 15 HVS 4c Follows 5.1...,,"Nov 12, 2016","May 12, 2016",Diana Y,"5,151",75
9,NaN,none specified,NaN,"Trad, Sport climbs",none specified,"Lives in Orting, WA, 26 years old, Male",Leads 5.1 2 6 II 7 MD 2a Follows 3rd 1- 1...,Leads 5.11a 6c 22 VII+ 22 E3 5c Follows 5...,3,2 days ago,"Feb 28, 2014",George Zack,"2,288",260
10,NaN,High Plains Drifter,NaN,"Sport, TR climbs",none specified,"Lives in Portland, OR, Male",Leads 5.10b 6a+ 19 VII- 19 E2 5b Follows ...,NaN,0,"Feb 22, 2017","Jul 21, 2014",Daniel Bookless,"5,457",65
11,NaN,none specified,NaN,Trad climbs none specified,none specified,"Lives in Leavenworth, WA, Male",NaN,NaN,,3 hours ago,"May 4, 2012",Sam Cannon,904,762
12,NaN,"Icicle Creek, Leavenworth",NaN,"Trad, Sport, TR, Gym climbs","Brewing (Pro), Paddleboarding, Backcountry Sk...","Lives in Chelan, WA, 32 years old, Male",Leads 5.7 5a 15 V+ 13 MVS 4b Follows 5.9 ...,Leads 5.5 4b 13 IV+ 11 MS 4a Follows 5.8 ...,0,"Mar 7, 2017","Jan 13, 2015",Gaarth,"4,498",90
13,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,2,56 mins ago,"Jul 22, 2012",Curtveld,"1,882",340
14,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,1,3 days ago,"Aug 31, 2009",Ian Dickson,"3,212",160
15,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs",none specified,"Lives in Seattle, WA, 30 years old, Male",Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,Leads 5.8 5b 16 VI- 15 HVS 4c Follows 5.1...,,19 hours ago,"Oct 24, 2015",Paul Carduner,-none-,0
16,Leads C1 Follows C1,I really can't list them all. Look for the o...,Leads WI6 Follows WI6,"Trad, Sport, Gym climbs",none specified,"Lives in Seattle, WA, Male",Leads 5.13b 8a 29 IX+ 30 E7 6c Follows 5....,Leads 5.10d 6b+ 21 VII+ 21 E3 5b Follows ...,,18 hours ago,"Jan 28, 2009",Jeff Hebert,107,"4,240"
17,NaN,"Colorado, Washington",NaN,"Trad, Sport climbs",none specified,"Lives in Spokane, WA, 22 years old, Male",Leads 5.11a 6c 22 VII+ 22 E3 5c Follows 5...,Leads 5.10d 6b+ 21 VII+ 21 E3 5b Follows ...,,2 days ago,"Jul 20, 2012",Dakota Bauman,"15,232",5
18,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,"Sep 6, 2016","Sep 3, 2015",Jason Muise,-none-,0
19,Leads C1 Follows C1,Thin Fingers,NaN,Trad climbs,none specified,"Lives in Bellingham, WA, 32 years old",NaN,Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,2,"Jan 19, 2017","Jun 6, 2011",michael faith,936,740
20,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,"Oct 18, 2016","Sep 10, 2015",Dan Sulpizi,"7,947",30
21,NaN,Yes,NaN,none specified,sometimes,"Lives in Tucson, Male",NaN,NaN,,1 day ago,"Dec 28, 2011",Kemper Brightman,335,"1,828"
22,NaN,"if i'm not cussing, it isn't worth climbing...",NaN,none specified,"judging stunt guitar, long walks on the beach...",NaN,NaN,NaN,3,2 hours ago,"Dec 1, 2004",slim,776,885
23,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,"Feb 20, 2017","May 26, 2015",Scott Everatt,-none-,0
24,NaN,"Multi-Pitch Trad, Multi-day Traverses, Mounta...",Leads WI2 Follows WI3,"Trad, Sport, TR, Gym climbs",Photography,"Lives in Seattle, WA, 31 years old, Male",Leads 5.8 5b 16 VI- 15 HVS 4c Follows 5.1...,Leads 5.7 5a 15 V+ 13 MVS 4b Follows 5.9 ...,13,11 hours ago,"Nov 25, 2015",Nat D,"1,552",425
25,Leads C0 Follows C1,"Stuart Glacier Couloir on Mt. Stuart, Liberty...",Leads WI5 Follows WI5,"Trad, Sport climbs","Mountaineering, Backpacking, Highpointing, an...","Lives in Spokane, WA, 29 years old, Male",Leads 5.11a 6c 22 VII+ 22 E3 5c Follows 5...,Leads 5.10d 6b+ 21 VII+ 21 E3 5b Follows ...,,7 hours ago,"Oct 24, 2011",Marlin Thorman,"1,801",355
26,NaN,"Moons of Pluto, Thieves in the temple, Perche...",NaN,"Trad, Sport, TR, Gym climbs",none specified,"Lives in Portland, OR, 33 years old, Male",Leads 5.12a 7a+ 25 VIII+ 25 E5 6a Follows ...,Leads 5.9 5c 17 VI 17 HVS 5a Follows 5.10...,7,3 days ago,"May 12, 2010",Peter Rakowitz,"2,463",235
27,NaN,Some good mulitpitch,NaN,"Trad, Sport climbs",none specified,"Lives in Everett, WA, 33 years old, Male",Leads 5.11b 6c 23 VIII- 23 E3 5c Follows ...,Leads 5.10b 6a+ 19 VII- 19 E2 5b Follows ...,,3 hours ago,"Nov 6, 2013",Andrew Davidson,647,"1,041"
28,Leads C0 Follows C5,"Triple Couloirs, Southwest Rib of South Early...",Leads WI3 Follows WI6,"Trad, Sport climbs","Black metal, cycling, adventure","Lives in Spokane, WA, 23 years old, Male",Leads 5.10c 6b 20 VII 20 E2 5b Follows 5....,Leads 5.9 5c 17 VI 17 HVS 5a Follows 5.10...,,4 hours ago,"Jun 8, 2013",Nick Sweeney,"1,154",582
29,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,9,"Nov 30, -0001","Nov 30, -0001",Abandoned User,-none-,0
30,NaN,New and just wanting to experience new places,NaN,"Sport, Gym climbs",none specified,"Lives in Oroville, WA, 49 years old, Male",Leads 5.6 4c 14 V 12 S 4b Follows 5.10a 6...,NaN,0,2 hours ago,"Apr 19, 2016",Steve Quick,"10,450",15
31,NaN,none specified,NaN,"Trad, Sport climbs",none specified,"Lives in Brush Prairie, Washington, 30 years ...",Leads 5.11a 6c 22 VII+ 22 E3 5c Follows 5...,Leads 5.10c 6b 20 VII 20 E2 5b Follows 5....,0,2 hours ago,"Mar 25, 2014",BrianWilson,"3,940",115
32,NaN,none specified,NaN,"Sport, TR, Gym climbs none specified",none specified,NaN,NaN,NaN,0,"Nov 19, 2014","Aug 17, 2009",laurichj,"2,758",200
33,Leads C5 Follows C5,none specified,NaN,,Your mom!,NaN,NaN,NaN,5,23 hours ago,"May 5, 2009",Rafe,"1,432",465
34,Leads C2 Follows C3,none specified,Leads WI2 Follows WI5,"Trad, Sport, TR, Gym climbs","Kayaking, Fly fishing, snowboarding","Lives in Kent, Wa, Male",Leads 5.10b 6a+ 19 VII- 19 E2 5b Follows ...,Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,8,"Nov 3, 2015","Sep 15, 2009",Tom Bath,238,"2,385"
35,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,,"Mar 1, 2017","Jan 3, 2013",dondo,-none-,0
36,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,1,"May 23, 2016","Oct 29, 2007",Benjamin Smith,"7,038",40
37,NaN,none specified,NaN,"Trad, Sport climbs",none specified,"Lives in Winthrop, WA, 34 years old, Female",Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,Leads 5.8 5b 16 VI- 15 HVS 4c Follows 5.1...,0,"Feb 20, 2017","Mar 31, 2014",jubalee,-none-,0
38,Leads C2 Follows C0,"Primrose Dihedrals, Standing Rock (Canyonland...",Leads WI2 Follows WI4,"Trad, Sport climbs",none specified,"Lives in Grand Canyon, AZ 86023, 33 years old...",Leads 5.10c 6b 20 VII 20 E2 5b Follows 5....,Leads 5.10c 6b 20 VII 20 E2 5b Follows 5....,30,4 days ago,"Apr 16, 2007",BenCooper,"1,766",365
39,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs",none specified,"Lives in Seattle, WA, 37 years old, Female",Leads 5.9 5c 17 VI 17 HVS 5a Follows 5.10...,Leads 4th 1 2 I 2 M 1b Follows 5.10d 6b+ ...,2,"Sep 18, 2014","Apr 12, 2009",Eliza Penick,"1,505",440
40,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,1 day ago,"Aug 23, 2016",Jesse Frankley,"16,105",5
41,NaN,Professor Pogue's Precarious Pinacle,NaN,"Trad, Sport, TR, Gym climbs","Mountaineering, Rafting, Surfing, Running, Cy...","Lives in Seattle, WA, 20 years old, Female",Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,Leads 5.6 4c 14 V 12 S 4b Follows 5.10a 6...,,2 days ago,"Jul 4, 2016",Madelynn Scherrer,"13,653",10
42,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs","Travel, Outdoors","Lives in Olympia, WA, 28 years old, Male",Leads 5.8 5b 16 VI- 15 HVS 4c Follows 5.1...,Leads 5.7 5a 15 V+ 13 MVS 4b Follows 5.10...,0,"Aug 24, 2015","Oct 24, 2014",Travis A,-none-,0
43,NaN,none specified,NaN,"Trad, Sport climbs",none specified,"Lives in Olympia, WA, 24 years old, Male",Leads 5.11d 7a 24 VIII 25 E5 6a Follows 5...,Leads 5.10d 6b+ 21 VII+ 21 E3 5b Follows ...,0,2 days ago,"Jul 27, 2012",A.wilk Wilk,"9,458",20
44,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs",none specified,"Lives in Seattle, WA, 35 years old, Male",Leads 5.10d 6b+ 21 VII+ 21 E3 5b Follows ...,Leads 5.10b 6a+ 19 VII- 19 E2 5b Follows ...,6,"Oct 20, 2016","May 7, 2013",JustinJones13,"1,385",485
45,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,"Dec 2, 2016","Aug 5, 2010",Schurman,-none-,0
46,NaN,none specified,NaN,none specified,none specified,NaN,NaN,NaN,0,"Feb 17, 2017","Sep 14, 2016",David Hornsby,-none-,0
47,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs","Backpacking, Reading, Running","Lives in Lake Stevens, 27 years old, Male",Leads 5.10a 6a 18 VI+ 18 E1 5a Follows 5....,Leads 4th 1 2 I 2 M 1b Follows 5.9 5c 17 ...,0,"Jun 15, 2016","Oct 8, 2014",Tom Pittman VIII,"13,853",8
48,NaN,none specified,NaN,none specified,none specified,"Lives in Seattle, Wa.",NaN,NaN,9,2 hours ago,"Feb 8, 2010",geoff georges,141,"3,490"
49,NaN,none specified,NaN,"Trad, Sport, TR, Gym climbs","Snowboarding, Camping, Photography","Lives in South Lake Tahoe, CA, 25 years old, ...",Leads 5.10c 6b 20 VII 20 E2 5b Follows 5....,Leads 5.9 5c 17 VI 17 HVS 5a Follows 5.10...,0,6 hours ago,"Apr 26, 2011",Matt..C,"11,792",10

In [89]:
df_users['name'].shape[0]

680